// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBDWj84IJM0u5RytGKzTy7BoJUf2hEdFY',
    appId: '1:266689150707:web:b33f32a945bdb478e84186',
    messagingSenderId: '266689150707',
    projectId: 'awesome-noti',
    authDomain: 'awesome-noti.firebaseapp.com',
    storageBucket: 'awesome-noti.firebasestorage.app',
    measurementId: 'G-SD4DVBW0LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtNTpqSTqaJJomvtgUvpMRJQSRFEzY1I',
    appId: '1:266689150707:android:5c8295243ee7ebd1e84186',
    messagingSenderId: '266689150707',
    projectId: 'awesome-noti',
    storageBucket: 'awesome-noti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC_uzz_fktqJOVL0daMZDpmEdS1WJFWsA',
    appId: '1:266689150707:ios:bbb2b28a65cfbb3ae84186',
    messagingSenderId: '266689150707',
    projectId: 'awesome-noti',
    storageBucket: 'awesome-noti.firebasestorage.app',
    iosBundleId: 'com.example.innitiConstro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC_uzz_fktqJOVL0daMZDpmEdS1WJFWsA',
    appId: '1:266689150707:ios:bbb2b28a65cfbb3ae84186',
    messagingSenderId: '266689150707',
    projectId: 'awesome-noti',
    storageBucket: 'awesome-noti.firebasestorage.app',
    iosBundleId: 'com.example.innitiConstro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBDWj84IJM0u5RytGKzTy7BoJUf2hEdFY',
    appId: '1:266689150707:web:ae86318935d4f6b7e84186',
    messagingSenderId: '266689150707',
    projectId: 'awesome-noti',
    authDomain: 'awesome-noti.firebaseapp.com',
    storageBucket: 'awesome-noti.firebasestorage.app',
    measurementId: 'G-MW95H29XP0',
  );
}
