import '../models/dummy_bundle_model.dart';
import '../models/dummy_product_model.dart';

class Dummy {
  /// List Of Dummy Products
  static List<ProductModel> products = [
    ProductModel(
      name: 'Perry\'s Ice Cream Banana',
      weight: '800 gm',
      cover: 'https://i.imgur.com/6unJlSL.png',
      images: ['https://i.imgur.com/6unJlSL.png'],
      price: 13,
      mainPrice: 15,
    ),
    ProductModel(
      name: 'Vanilla Ice Cream Banana',
      weight: '500 gm',
      cover: 'https://i.imgur.com/oaCY49b.png',
      images: ['https://i.imgur.com/oaCY49b.png'],
      price: 12,
      mainPrice: 15,
    ),
    ProductModel(
      name: 'Meat',
      weight: '1 Kg',
      cover: 'https://i.imgur.com/5wghZji.png',
      images: ['https://i.imgur.com/5wghZji.png'],
      price: 15,
      mainPrice: 18,
    ),
  ];

  /// List Of Dummy Bundles
  static List<BundleModel> bundles = [
    BundleModel(
      name: 'Bundle Pack',
      cover: 'https://i.imgur.com/Y0IFT2g.png',
      itemNames: ['Onion, Oil, Salt'],
      price: 35,
      mainPrice: 50.32,
    ),
    BundleModel(
      name: 'Medium Spices Pack',
      cover: 'https://i.postimg.cc/qtM4zj1K/packs-2.png',
      itemNames: ['Onion, Oil, Salt'],
      price: 35,
      mainPrice: 50.32,
    ),
    BundleModel(
      name: 'Bundle Pack',
      cover: 'https://i.postimg.cc/MnwW8WRd/pack-1.png',
      itemNames: ['Onion, Oil, Salt'],
      price: 35,
      mainPrice: 50.32,
    ),
    BundleModel(
      name: 'Bundle Pack',
      cover: 'https://i.postimg.cc/k2y7Jkv9/pack-4.png',
      itemNames: ['Onion, Oil, Salt'],
      price: 35,
      mainPrice: 50.32,
    ),
  ];
}

List<Map<String, dynamic>> labours = [
  {
    'id': 38,
    'name': 'Jayesh',
    'labourCategory': 'Mason',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-38',
    'status': true,
  },
  {
    'id': 37,
    'name': 'Rajesh',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-37',
    'status': false,
  },
  {
    'id': 35,
    'name': 'Rajesh Bhai',
    'labourCategory': '',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-35',
    'status': true,
  },
  {
    'id': 34,
    'name': 'Jayraj Zala',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-34',
    'status': false,
  },
  {
    'id': 33,
    'name': 'Jaynam',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-33',
    'status': true,
  },
  {
    'id': 39,
    'name': 'Bhipendra Mehta',
    'labourCategory': 'Electrician',
    'company': 'Bhavesh Suppliers',
    'contact': '555-555-39',
    'status': false,
  },
  {
    'id': 38,
    'name': 'Jayesh',
    'labourCategory': 'Mason',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-38',
    'status': true,
  },
  {
    'id': 37,
    'name': 'Rajesh',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-37',
    'status': false,
  },
  {
    'id': 35,
    'name': 'Rajesh Bhai',
    'labourCategory': '',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-35',
    'status': false,
  },
  {
    'id': 38,
    'name': 'Jayesh',
    'labourCategory': 'Mason',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-38',
    'status': true,
  },
  {
    'id': 37,
    'name': 'Rajesh',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-37',
    'status': true,
  },
  {
    'id': 35,
    'name': 'Rajesh Bhai',
    'labourCategory': '',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-35',
    'status': true,
  },
  {
    'id': 34,
    'name': 'Jayraj Zala',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-34',
    'status': false,
  },
  {
    'id': 33,
    'name': 'Jaynam',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-33',
    'status': false,
  },
  {
    'id': 39,
    'name': 'Bhipendra Mehta',
    'l': 'Electrician',
    'company': 'Bhavesh Suppliers',
    'contact': '555-555-39',
    'status': false,
  },
  {
    'id': 38,
    'name': 'Jayesh',
    'labourCategory': 'Mason',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-38',
    'status': true,
  },
  {
    'id': 37,
    'name': 'Rajesh',
    'labourCategory': '',
    'company': 'Aj Contractors',
    'contact': '555-555-37',
    'status': false,
  },
  {
    'id': 35,
    'name': 'Rajesh Bhai',
    'labourCategory': '',
    'company': 'Bhoomi Contractor',
    'contact': '555-555-35',
    'status': false,
  },
];
